"""
Executor Node for mit-aichat.

The "Doer" node that executes the tool plan generated by the Analyzer.
Communicates with the MCP server to fetch infrastructure data.
Adds results to message history for the iterative loop.
"""

import json
from typing import Any, Dict, List

from langchain_core.messages import AIMessage

from app.core.state import AgentState
from app.tools.mcp.client import MCPClient


async def execute_node(state: AgentState) -> Dict[str, Any]:
    """
    Execute the tool plan from the analyzer.

    Iterates through the planned tools, executes each via MCP client,
    and adds results both to tool_results and to message history
    (so the Analyzer can see them in the next iteration).

    Args:
        state: Current agent state containing tool_plan.

    Returns:
        Dictionary with tool_results and messages to update state.
    """
    tool_plan = state.get("tool_plan")

    # Handle empty or missing plan
    if not tool_plan:
        return {"tool_results": []}

    client = MCPClient()
    results: List[Dict[str, Any]] = []
    messages: List[AIMessage] = []

    for item in tool_plan:
        tool_name = item.get("tool", "")
        tool_args = item.get("args", {})

        if not tool_name:
            results.append({
                "tool": tool_name,
                "error": "Missing tool name in plan",
                "success": False,
            })
            continue

        result = await client.execute_tool(tool_name, tool_args)

        # Tag result with the tool name for context
        tool_result = {
            "tool": tool_name,
            "args": tool_args,
            "result": result,
        }
        results.append(tool_result)

        # Add to message history so Analyzer can see it in next iteration
        # Truncate large results to prevent context overflow
        result_str = json.dumps(result, default=str)
        if len(result_str) > 3000:
            result_str = result_str[:3000] + "... (truncated)"

        messages.append(AIMessage(
            content=f"[Tool Result: {tool_name}]\nArgs: {json.dumps(tool_args)}\nResult:\n{result_str}"
        ))

    return {
        "tool_results": results,
        "messages": messages,  # Appends to history via operator.add
    }
