"""
Executor Node for mit-aichat.

The "Doer" node that executes the tool plan generated by the Analyzer.
Communicates with the MCP server to fetch infrastructure data.
"""

from typing import Any, Dict, List

from app.core.state import AgentState
from app.tools.mcp.client import MCPClient


async def execute_node(state: AgentState) -> Dict[str, Any]:
    """
    Execute the tool plan from the analyzer.

    Iterates through the planned tools, executes each via MCP client,
    and aggregates all results.

    Args:
        state: Current agent state containing tool_plan.

    Returns:
        Dictionary with tool_results to update state.
    """
    tool_plan = state.get("tool_plan")

    # Handle empty or missing plan
    if not tool_plan:
        return {"tool_results": []}

    client = MCPClient()
    results: List[Dict[str, Any]] = []

    for item in tool_plan:
        tool_name = item.get("tool", "")
        tool_args = item.get("args", {})

        if not tool_name:
            results.append({
                "tool": tool_name,
                "error": "Missing tool name in plan",
                "success": False,
            })
            continue

        result = await client.execute_tool(tool_name, tool_args)

        # Tag result with the tool name for context in response generation
        results.append({
            "tool": tool_name,
            "args": tool_args,
            "result": result,
        })

    return {"tool_results": results}
